//nos explica que va sucediendo en nuestra aplicacion
//creacion de registro
export const AGREGAR_VEHICULO        = 'AGREGAR_VEHICULO';
export const AGREGAR_VEHICULO_EXITO  = 'AGREGAR_VEHICULO_EXITO';
export const AGREGAR_VEHICULO_ERROR  = 'AGREGAR_VEHICULO_ERROR';

//obtencion de vehiculos
export const INICIAR_DESCARGA_VEHICULOS = 'INICIAR_DESCARGA_VEHICULOS';
export const DESCARGA_VEHICULOS_EXITO   = 'DESCARGA_VEHICULOS_EXITO';
export const DESCARGA_VEHICULOS_ERROR   = 'DESCARGA_VEHICULOS_ERROR';

//obtencion para eliminar
export const OBTENER_VEHICULO_ELIMINAR       = 'OBTENER_VEHICULO_ELIMINAR';
export const OBTENER_VEHICULO_ELIMINAR_EXITO = 'OBTENER_VEHICULO_ELIMINAR_EXITO';
export const OBTENER_VEHICULO_ELIMINAR_ERROR = 'OBTENER_VEHICULO_ELIMINAR_ERROR';

//obtencion para editar
export const OBTENER_VEHICULO_EDITAR       = 'OBTENER_VEHICULO_EDITAR';
export const INICIAR_EDICION_VEHICULO      = 'INICIAR_EDICION_VEHICULO';
export const OBTENER_VEHICULO_EDITAR_EXITO = 'OBTENER_VEHICULO_EDITAR_EXITO';
export const OBTENER_VEHICULO_EDITAR_ERROR = 'OBTENER_VEHICULO_EDITAR_ERROR';

//obtencion services
export const INICIAR_DESCARGA_SERVICE = 'INICIAR_DESCARGA_SERVICE';
export const DESCARGA_SERVICE_EXITO   = 'DESCARGA_SERVICE_EXITO';
export const DESCARGA_SERVICE_ERROR   = 'DESCARGA_SERVICE_ERROR';

//alerta
export const MOSTRAR_ALERTA  = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA  = 'OCULTAR_ALERTA';